### ISSUE TITLE
适配从其它页面进入网页的多窗口

### ISSUE THREAD

**Issue by Landidi666** [zhangnew/WechatMultiWebview#1]
我的微信版本8.0.40，进入公众号文章可以正确出现多窗口，但是从聊天或朋友圈进入网页没有多窗口。希望适配更多的页面

**Comment by zhangnew** [comment]
我是 Google Play 8.0.37 测试没问题，你可以把对应的 Activity 拿出来看一下，比如用 Thanox 设置里面的 `显示当前活动` 功能，或者自己搜一下其他方法，adb 也可以

**Comment by Landidi666** [comment]
下图是公众号文章的Activity
![62bb009a3aaa0d197dfb4516057e749](https://github.com/zhangnew/WechatMultiWebview/assets/104005371/7a66dc37-d9d3-4107-846f-96fefe5766e9)
下图是从聊天和收藏进入网页的Activity
![a849676be30938c9bbf05656bbe97c4](https://github.com/zhangnew/WechatMultiWebview/assets/104005371/2a8fa17a-20e6-4e7f-86cf-7ae0f6285a7c)

**Comment by zhangnew** [comment]
试下这个 https://github.com/zhangnew/WechatMultiWebview/releases/tag/1.3

**Comment by Landidi666** [comment]
现在可以了，完美！
